version: "3.7"
services:
  boutique_service:
    build:
      context: ./Micro-Services/boutique-service
    container_name: boutique-service
    restart: always
    ports:
      - 4570:8080
    networks:
      - palgo-network
    hostname: boutique_service

  incubateur_service:
    build:
      context: ./Micro-Services/incubateur-service
    container_name: incubateur-service
    restart: always
    ports:
      - 4571:8080
    networks:
      - palgo-network
    hostname: incubateur_service

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  palgo-network:
    name: palgo-network
    driver: bridge