version: "3.7"
services:
  boutique_service:
    build:
      context: ./Micro-Services/boutique-service
    container_name: boutique-service
    restart: always
    ports:
      - 4570:8080
    networks:
      - palgo-network
    hostname: boutique_service

networks:
  palgo-network:
    name: palgo-network
    driver: bridge