version: "3.7"
services:
  boutique_service:
    build:
      context: ./Micro-Services/boutique-service
    container_name: boutique-service
    restart: always
    ports:
      - 4570:8080
    networks:
      - palgo-network
    hostname: boutique_service

  oeuf_service:
    build:
      context: ./Micro-Services/oeuf-service
    container_name: oeuf-service
    restart: always
    ports:
      - 4571:8080
    networks:
      - palgo-network
    hostname: oeuf_service

  monstre_service:
    build:
      context: ./Micro-Services/monstre-service
    container_name: monstre-service
    restart: always
    ports:
      - 4572:8080
    networks:
      - palgo-network
    hostname: monstre_service

  incubateur_service:
    build:
      context: ./Micro-Services/incubateur-service
    container_name: incubateur-service
    restart: always
    ports:
      - 4573:8080
    networks:
      - palgo-network
    hostname: incubateur_service

  inventaire_service:
    build:
      context: ./Micro-Services/inventaire-service
    container_name: inventaire-service
    restart: always
    ports:
      - 4574:8080
    networks:
      - palgo-network
    hostname: inventaire_service

  hero_service:
    build:
      context: ./Micro-Services/hero-service
    container_name: hero-service
    restart: always
    ports:
      - 4575:8080
    networks:
      - palgo-network
    hostname: hero_service

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  palgo-network:
    name: palgo-network
    driver: bridge